# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attachment-san}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran", "Manfred Stienstra"]
  s.date = %q{2009-11-19}
  s.description = %q{Rails plugin for easy and rich attachment manipulation.}
  s.email = ["eloy@fngtps.com", "manfred@fngtps.com"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "examples/photo.rb",
     "examples/photos_controller.rb",
     "examples/post.rb",
     "lib/attachment_san.rb",
     "lib/attachment_san/has.rb",
     "lib/attachment_san/test/helper.rb",
     "lib/attachment_san/test/rails.png",
     "lib/attachment_san/variant.rb",
     "napkin.rb",
     "rails/init.rb",
     "test/attachment_san_test.rb",
     "test/fixtures/models/attachment.rb",
     "test/fixtures/models/document.rb",
     "test/fixtures/models/options_stub.rb",
     "test/has_test.rb",
     "test/lib/schema.rb",
     "test/test_helper.rb",
     "test/variant_test.rb"
  ]
  s.homepage = %q{http://github.com/Fingertips/attachment-san}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails plugin for easy and rich attachment manipulation.}
  s.test_files = [
    "test/attachment_san_test.rb",
     "test/fixtures/models/attachment.rb",
     "test/fixtures/models/document.rb",
     "test/fixtures/models/options_stub.rb",
     "test/has_test.rb",
     "test/lib/schema.rb",
     "test/test_helper.rb",
     "test/variant_test.rb",
     "examples/photo.rb",
     "examples/photos_controller.rb",
     "examples/post.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

